### ISSUE TITLE
Question about the number of queries calculation?

### ISSUE THREAD

**Issue by machanic** [snu-mllab/parsimonious-blackbox-attack#2]
I am confused a problem related to the number of queries computation.
Because you feed a batch of images with batch size of `bend-bstart` to the target model, located in https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/master/cifar10/attacks/local_search_helper.py#L238

However, the number queries is calculated based on ` num_queries += success_indices[0] + 1`,  rather than `num_queries += bend - bstart`, which is located in https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/master/cifar10/attacks/local_search_helper.py#L246
Why? Is this bug?

**Comment by dssrgu** [comment]
Hello,

In black-box attacks literature it is standard to not count the queries for success-checking, since (a) these can just be integrated with the queries themselves (not doing so is just a matter of code cleanliness), and (b) these queries don’t contribute to the attack itself.

Regarding (a), `num_queries += bend - bstart` part you mentioned is taken into account in https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/71b4a16e03b2c338e016b9296ce7ac4f690d1a0e/cifar10/attacks/local_search_helper.py#L248 , which runs when the success-checking fails.

Thank you.

**Comment by symoon11** [comment]
This query count can be obtained when we set batch_size = 1 in the following line.
https://github.com/snu-mllab/parsimonious-blackbox-attack/blob/71b4a16e03b2c338e016b9296ce7ac4f690d1a0e/cifar10/attacks/local_search_helper.py#L223
We don't have to compute the marginal gains batch-wise. However, for the efficiency of the experiment, we set the batch_size = 100.
